name: React Web Amazon CI & CD Workflow

on:
  push:
    branches: [master, develop, 'feature/**', 'release/**']
  pull_request:
    branches: [master, develop, 'feature/**', 'release/**']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install Dependencies
    - run: yarn install
    - name: yarn test 
    - run: CI=true yarn test --coverage
